### ISSUE TITLE
➕ Add Polygon Amoy Testnet Deployment

### ISSUE THREAD

**Issue by area** [pcaversaccio/createx#100]
### Chain Name

Polygon Amoy Testnet

### Chain ID

80002

### RPC URL

https://rpc-amoy.polygon.technology/

### Block Explorer URL

https://www.oklink.com/amoy‍

### Deployment Funds

Yes

**Comment by pcaversaccio** [comment]
@area any insights if the test network will also be supported via Etherscan & Sourcify?

**Comment by area** [comment]
None, I'm afraid. I just know what's in the [blog post](https://polygon.technology/blog/introducing-the-amoy-testnet-for-polygon-pos)!

**Comment by pcaversaccio** [comment]
> None, I'm afraid. I just know what's in the [blog post](https://polygon.technology/blog/introducing-the-amoy-testnet-for-polygon-pos)!

I talked yesterday to the Polygon team and they are working on it. Hopefully in the upcoming days, Etherscan should have a running instance. I will wait for this instance to be up and running so I can deploy & verify it on all block explorers at once and don't have to track it separately. I hope that works for you.

**Comment by area** [comment]
Makes sense. I'll keep an eye out!

**Comment by pcaversaccio** [comment]
Ok Etherscan still hasn't shipped it and thus I decided to deploy now. Here you go: [Polygon Sepolia Testnet (Amoy)](https://www.oklink.com/amoy/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).

Please note that OKLink explorer contract verification [API endpoint](https://www.oklink.com/docs/en/#on-chain-tools-contract-verification-verify-source-code) doesn't allow to remove the metadata hash from the bytecode and thus I can't verify the contract currently.

**Comment by pcaversaccio** [comment]
UPDATE: Etherscan Amoy is now live and I verified `CreateX` [here](https://amoy.polygonscan.com/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed). Enjoy!
