### ISSUE TITLE
💥 Build a Simple SDK for Use Without Knowledge of the Interface, ABI, or Typechain Definitions

### ISSUE THREAD

**Issue by tornadocontrib** [pcaversaccio/createx#101]
### Describe the desired feature:

Would be great if we could have some simple function exposed that could be used to deploy contracts with ethers.js provider ( or viem provider but I don't use viem ).

Something like

```
async function deployCreateX(signer: SignerWithAddress, salt: BytesLike, initCode: bytesLike): Promise<ContractResponse> {
   return await CreateX.deployCreate2(salt, initCode);
}
```

But with this function we don't need to import createx's ABI or type definitions for every projects.

**Comment by pcaversaccio** [comment]
@tornadocontrib I built exactly such an "SDK" via my Hardhat plugin [`xdeployer`](https://github.com/pcaversaccio/xdeployer). No need to import anything, just `npm` install it and hit `npx hardhat xdeploy` :). Via the [`3.0.0`](https://github.com/pcaversaccio/xdeployer/releases/tag/v3.0.0) release, `CreateX` got added.

A couple of caveats however:
- [`xdeployer`](https://github.com/pcaversaccio/xdeployer) only supports `CREATE2` deployments. So if you want to make use of `CREATE`, `CREATE3`, or minimal proxy contracts (a.k.a. `Clones`), you need to fork  [`xdeployer`](https://github.com/pcaversaccio/xdeployer) and adjust according to your needs.
- If you use a vanity address via [`createXcrunch`](https://github.com/HrikB/createXcrunch), please be aware that I hash again the `salt` value (which is submitted a string value in the Hardhat config) [here](https://github.com/pcaversaccio/xdeployer/blob/857a43015dad8ef7d5bfec126a03722f7328e32b/src/index.ts#L146) before deploying. So you would need to adjust this as well before deploying.

The underlying reason behind these design decisions was to make it agnostic to any kind of `CREATE2` factory that might need different handling of `salt` values and/or have different functions.

I'm closing this issue as I deem it as resolved. Please comment or reopen if you disagree.

**Comment by tornadocontrib** [comment]
@pcaversaccio Yes I saw it but since only works in Hardhat ( and since they are moving to a new deployment system called ignition ) would be great if you could create a type export with the function that could work with ethers.js

**Comment by pcaversaccio** [comment]
> @pcaversaccio Yes I saw it but since only works in Hardhat ( and since they are moving to a new deployment system called ignition ) would be great if you could create a type export with the function that could work with ethers.js

Different people have different tastes and thus we let the community build external tooling and list it [here](https://github.com/pcaversaccio/createx#integration-with-external-tooling). Furthermore, you can find and download the ABI in the various formats [here](https://createx.rocks/abi). If you build a tooling that integrates `CreateX`, I will happily list it there as well. If you want to generate the `typechain-types` for `CreateX`, you can simply clone the `CreateX` repository and compile it with Hardhat: `npx hardhat compile`. I attached them to this comment as well.

[typechain-types.zip](https://github.com/pcaversaccio/createx/files/14816094/typechain-types.zip)

**Comment by pcaversaccio** [comment]
Let me mention that `CreateX` is the built-in factory for Hardhat Ignition (see [here](https://hardhat.org/ignition/docs/guides/create2).
