### ISSUE TITLE
➕ Add Mode Sepolia Testnet Deployment

### ISSUE THREAD

**Issue by simplyoptimistic** [pcaversaccio/createx#104]
### Chain Name

Mode Sepolia Testnet

### Chain ID

919

### RPC URL

https://sepolia.mode.network/

### Block Explorer URL

https://sepolia.explorer.mode.network/

### Deployment Funds

Yes

**Comment by pcaversaccio** [comment]
Deployed: [Mode Sepolia Testnet](https://sepolia.explorer.mode.network/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
