### ISSUE TITLE
➕ Add Build on Bitcoin (BOB) Main Network Deployment

### ISSUE THREAD

**Issue by simplyoptimistic** [pcaversaccio/createx#113]
### Chain Name

Build On Bitcoin

### Chain ID

60808

### RPC URL

https://rpc.gobob.xyz/

### Block Explorer URL

https://explorer.gobob.xyz/

### Deployment Funds

Yes

### Other Notes
https://docs.gobob.xyz/docs/build/getting-started/networks

Feel free to keep 0.1E, send the rest back. Thanks.

**Comment by pcaversaccio** [comment]
Deployed via https://github.com/pcaversaccio/createx/pull/114. Refund transaction: https://explorer.gobob.xyz/tx/0x923d39f2cb7d43efce572c73e5957258b3e80eff019b4285d9c317942881fa77.
