### ISSUE TITLE
➕ Add Fraxtal Main Network Deployment

### ISSUE THREAD

**Issue by 0xAtum** [pcaversaccio/createx#115]
### Chain Name

Fraxtal

### Chain ID

252

### RPC URL

https://rpc.frax.com

### Block Explorer URL

https://fraxscan.com/

### Deployment Funds

Yes

P.S: Keep the rest as donation

**Comment by pcaversaccio** [comment]
Deployed [here](https://fraxscan.com/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
