### ISSUE TITLE
💥 Deploy With Nick's Method

### ISSUE THREAD

**Issue by pegahcarter** [pcaversaccio/createx#120]
### Describe the desired feature:

"In summary, this method allows the execution of a transaction without being signed by a private key (Keyless), thus generating a “single-use uncontrollable address” just for the purpose of executing a transaction from it."

https://yamenmerhi.medium.com/nicks-method-ethereum-keyless-execution-168a6659479c

**Comment by pcaversaccio** [comment]
We offer 3 presigned transactions so anyone can deploy themselves. Please see [here](https://github.com/pcaversaccio/createx/discussions/61#discussioncomment-7937359) for the details on why we chose the current approach. Nick's method doesn't scale unfortunately.

**Comment by pcaversaccio** [comment]
> @pcaversaccio can you help me understand how this doesn't scale?  From my understanding we can hardcode v, r, s and anyone can submit the tx to create the `CreateXFactory` through the returned address.

Chains might not support pre-[EIP-155](https://eips.ethereum.org/EIPS/eip-155) transactions (like Canto, see also [here](https://github.com/foundry-rs/foundry/issues/3772)), which are required for Nick's method, or have different gas limit requirements (like Filecoin).

**Comment by pegahcarter** [comment]
I believe the gas limit requirements can be worked around with an abnormally high gas limit.  So then it seems like this solution would only work on EIP-155 forward-compatible chains.

**Comment by pcaversaccio** [comment]
> I believe the gas limit requirements can be worked around with an abnormally high gas limit.  So then it seems like this solution would only work on EIP-155 forward-compatible chains.

Not really, because you can't broadcast a transaction on Ethereum with e.g. 60M gas (30M is the maximum allowed on Ethereum mainnet), which is required by Filecoin.

**Comment by pegahcarter** [comment]
Got it, thanks!  Too bad there's not a 100% trustless way.
