### ISSUE TITLE
➕ Add Taraxa Test and Main Network Deployments

### ISSUE THREAD

**Issue by VargaElod23** [pcaversaccio/createx#123]
### Chain Name

Taraxa Mainnet & Testnet

### Chain ID

841 & 842

### RPC URL

https://rpc.mainnet.taraxa.io & https://rpc.mainnet.taraxa.io

### Block Explorer URL

https://mainnet.explorer.taraxa.io/ & https://testnet.explorer.taraxa.io/

### Deployment Funds

Yes

**Comment by VargaElod23** [comment]
@pcaversaccio please deploy on testnet next week as it will be reset today.

**Comment by pcaversaccio** [comment]
@VargaElod23 just to confirm: Taraxa is EVM-equivalent?

**Comment by VargaElod23** [comment]
EVM-native, yes @pcaversaccio

**Comment by pcaversaccio** [comment]
Gotcha - can you ping me here when the test network has been reset please.

**Comment by pcaversaccio** [comment]
> yes ofc, @pcaversaccio . In the meantime, could you do the mainnet deployment?

I can't do it today, maybe tomorrow, but I would prefer doing both in one go because it's an overhead for me otherwise.

**Comment by VargaElod23** [comment]
If you could, please do it tomorrow as this is a blocker currently on setting up our infra for mainnet, @pcaversaccio

**Comment by pcaversaccio** [comment]
> If you could, please do it tomorrow as this is a blocker currently on setting up our infra for mainnet, @pcaversaccio

I will first do the testnet deployment, to ensure anything works as intended (i.e. the deployment address is correct and the `CREATE` and `CREATE2` opcodes work as expected on your chain). After that check, I will deploy it on mainnet.

**Comment by pcaversaccio** [comment]
@VargaElod23 can you send me some funds to deploy on testnet please?

**Comment by pcaversaccio** [comment]
I used your faucet but it doesn't work...

**Comment by VargaElod23** [comment]
Yes, I sent some @pcaversaccio . Testnet has been reset yesterday evening, hence the volatility in the infra. We'll be fixing stuff today. Also, you should have mainnet funds.

**Comment by pcaversaccio** [comment]
> Yes, I sent some @pcaversaccio . Testnet has been reset yesterday evening, hence the volatility in the infra. We'll be fixing stuff today. Also, you should have mainnet funds.

I can see the mainnet funds but not the testnet funds: https://testnet.explorer.taraxa.io/address/0xed456e05caab11d66c4c797dd6c1d6f9a7f352b5.

**Comment by pcaversaccio** [comment]
> > Yes, I sent some @pcaversaccio . Testnet has been reset yesterday evening, hence the volatility in the infra. We'll be fixing stuff today. Also, you should have mainnet funds.
> 
> I can see the mainnet funds but not the testnet funds: https://testnet.explorer.taraxa.io/address/0xed456e05caab11d66c4c797dd6c1d6f9a7f352b5.

I managed to get some funds from the faucet and now wanting to send it to my deployer address: it's pending since 20mins: https://testnet.explorer.taraxa.io/tx/0xfaea93414b5d7f5af657ae945a31cac2857381649ff37a66936a144a5d5c738b. I'm sorry man, but this is so fucked up. Will probably take a look at Taraxa again next week... without testnet deployment am not gonna do prod.

**Comment by pcaversaccio** [comment]
Hmm looks like your test network is done @VargaElod23 
![image](https://github.com/pcaversaccio/createx/assets/25297591/d461cda0-8872-49e5-8ae2-48cf50d04b7b)

**Comment by VargaElod23** [comment]
Yes, we're resetting once more today. Unfortunate, but this is why testnets are. We were too aggressive in some block production ratios.

**Comment by VargaElod23** [comment]
The reset was successful & the faucet is working now. Regardless, I sent you some TARA on testnet @pcaversaccio. FYI we don't have Etherscan like API for contract verifications inside the Explorer yet.

**Comment by pcaversaccio** [comment]
> The reset was successful & the faucet is working now. Regardless, I sent you some TARA on testnet @pcaversaccio. FYI we don't have Etherscan like API for contract verifications inside the Explorer yet.

Hmm I can't see it here: https://testnet.explorer.taraxa.io/address/0xed456e05caab11d66c4c797dd6c1d6f9a7f352b5?

**Comment by pcaversaccio** [comment]
> > The reset was successful & the faucet is working now. Regardless, I sent you some TARA on testnet @pcaversaccio. FYI we don't have Etherscan like API for contract verifications inside the Explorer yet.
> 
> Hmm I can't see it here: https://testnet.explorer.taraxa.io/address/0xed456e05caab11d66c4c797dd6c1d6f9a7f352b5?

I think your test network has a serious issue: https://testnet.explorer.taraxa.io/tx/0xf6ee7a9a9c97103b5a47c8696e1881f53ea8c012fa12152e1495712e382a50ac. I used `nonce = 2` on purpose here to check for an issue and indeed it got confirmed. The tx should be pending until the txs with `nonce = 0` and `nonce = 1` went through...
