### ISSUE TITLE
➕ Add World Chain Test and Main Network Deployments

### ISSUE THREAD

**Issue by dysfunctor** [pcaversaccio/createx#136]
### Chain Name

World Chain

### Chain ID

480

### RPC URL

https://worldchain-mainnet.g.alchemy.com/public

### Block Explorer URL

https://worldchain-mainnet.explorer.alchemy.com/

### Deployment Funds

No

**Comment by pcaversaccio** [comment]
Hey, thanks for opening the request but without funds on my deployer account `0xeD456e05CaAb11d66C4c797dD6c1D6f9A7F352b5`, there will be no deployment.

**Comment by pcaversaccio** [comment]
Deployed on test and mainnet:
- [World Chain Sepolia Testnet](https://worldchain-sepolia.explorer.alchemy.com/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed),
- [World Chain](https://worldchain-mainnet.explorer.alchemy.com/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
