### ISSUE TITLE
💥 How to Compute the `CREATE2` Deployment Address?

### ISSUE THREAD

**Issue by eyalc900** [pcaversaccio/createx#140]
### Describe the desired feature:

the `deployCreate2(salt,initCode)` generates a deterministic address for the target contract.
But how can i get that address beforehand?
off-chain, I can do eth_call to get it, but on-chain (or foundry solidity script), we need a view function.

There is a view function `computeCreate2Address(salt,initCodeHash)` but it CANT be used:
the reason is that deployCreate2 doesn't use the salt as-is, but "guard" it. even simple salt like "0" is replaced.
There is also on view function to calculate the guarded value.

- The documentation should be fixed, as the meaning of "salt" is completely different between those function families.
- add a function that return the address of computeCreate2Address
- or at minimum, add a view function that "guard" the salt.

### Workaround

The following code can calculate the address in a script.
It has 2 shortcomings:
- besides being ugly 2-method wrapper, it wastes actual deployment gas, and thus can't be used on a real network.
- It can't calculate the address if the contract is already deployed.

```
   function internalDeployAddress(bytes32 salt, bytes memory initCode) public {
        address addr = createX.deployCreate2(salt, initCode);
        assembly {
            mstore(0x0, addr)
            revert(0,32)
        }
    }

    //workaround for a missing getDeployCreate2Address in ICreateX
    function getDeployAddress(bytes32 salt, bytes memory initCode) internal returns (address ret) {
        try this.internalDeployAddress(salt, initCode) {
        } catch (bytes memory reason) {
            (ret) = abi.decode(reason, (address));
        }
    }
```

**Comment by pcaversaccio** [comment]
Hey, so the address can be calculated correctly if you understand how the `salt` value is guarded: https://github.com/pcaversaccio/createx/blob/71925dd64d321055788cbb50bf24448cb5878f01/src/CreateX.sol#L873-L912

Let's assume you use your own random `salt` value, in that case you can use the function `computeCreate2Address(bytes32 salt, bytes32 initCodeHash)` with the `salt` value set equal to `keccak256(abi.encode(salt))`. You can easily calculate the deployment address for all different variations of the `salt` beforehand except for the pseudorandom case. All it takes is to understand how the `salt` value is guarded.

If you really need to incorporate the `_guard` logic into your contract, you can directly inherit from the `CreateX` contract the `_guard` function:

```solidity
// SPDX-License-Identifier: AGPL-3.0-only
pragma solidity 0.8.23;

import {CreateX} from "./CreateX.sol";

contract A is CreateX {
    address internal constant _CREATEX = 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed;

    function getDeployAddress(bytes32 salt, bytes32 initCodeHash) public view returns (address computedAddress) {
        return CreateX(_CREATEX).computeCreate2Address(_guard(salt), initCodeHash);
    }
}
```

The code has been frozen long time ago and no changes will be applied to the `CreateX` source code. I will amend the documentation however in case someone else faces the same issue as you.
