### ISSUE TITLE
➕ Add Plume Test Network Deployment

### ISSUE THREAD

**Issue by eyqs** [pcaversaccio/createx#142]
### Chain Name

Plume Testnet

### Chain ID

98864

### RPC URL

https://test-rpc.plumenetwork.xyz

### Block Explorer URL

https://test-explorer.plumenetwork.xyz

### Deployment Funds

Yes

**Comment by pcaversaccio** [comment]
Deployed: https://test-explorer.plumenetwork.xyz/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed.

**Comment by eyqs** [comment]
Thank you very much!
