### ISSUE TITLE
➕ Add XDC Test Network (Apothem) Deployment

### ISSUE THREAD

**Issue by yudikubota** [pcaversaccio/createx#144]
### Chain Name

XDC Apothem Network

### Chain ID

51

### RPC URL

https://erpc.apothem.network

### Block Explorer URL

https://apothem.xdcscan.io/

### Deployment Funds

Yes

**Comment by pcaversaccio** [comment]
Deployed here: https://apothem.xdcscan.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed.
