### ISSUE TITLE
➕ Add XDC Main Network Deployment

### ISSUE THREAD

**Issue by yudikubota** [pcaversaccio/createx#145]
### Chain Name

XinFin Network

### Chain ID

50

### RPC URL

https://rpc.xinfin.network

### Block Explorer URL

https://xdcscan.io/

### Deployment Funds

Yes

**Comment by pcaversaccio** [comment]
Deployed here: https://xdcscan.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed.
