### ISSUE TITLE
➕ Add SX Network Test and Main Network Deployments

### ISSUE THREAD

**Issue by lakshans** [pcaversaccio/createx#148]
### Chain Name

SX Network

### Chain ID

4162

### RPC URL

https://rpc.sx-rollup.gelato.digital

### Block Explorer URL

https://explorerl2.sx.technology

### Deployment Funds

Yes

**Comment by pcaversaccio** [comment]
@lakshans can you please also fund my deployer address on the Toronto test network. I always first deploy on the test network to ensure that it works as intended.

**Comment by lakshans** [comment]
Thanks @pcaversaccio. I've added funds on the test network: https://explorerl2.toronto.sx.technology/address/0xeD456e05CaAb11d66C4c797dD6c1D6f9A7F352b5

**Comment by pcaversaccio** [comment]
> https://explorerl2.toronto.sx.technology

Thx - the RPC for your Toronto test network in the [docs](https://docs.sx.technology/developers/network-details) is the RPC for the old test network. It should be updated to the correct RPC URL `https://rpc.sx-rollup-testnet.t.raas.gelato.cloud`.

**Comment by pcaversaccio** [comment]
Deployed:
- [SX Network Sepolia Testnet (Toronto)](https://explorerl2.toronto.sx.technology/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed),
- [SX Network](https://explorerl2.sx.technology/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
