### ISSUE TITLE
➕ Add Story Odyssey Test Network Deployment

### ISSUE THREAD

**Issue by BlazeWasHere** [pcaversaccio/createx#156]
### Chain Name

Story Odyssey Testnet

### Chain ID

1516

### RPC URL

https://odyssey.storyrpc.io

### Block Explorer URL

https://odyssey.storyscan.xyz/

### Deployment Funds

Yes

**Comment by pcaversaccio** [comment]
Deployed: https://odyssey.storyscan.xyz/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed.
