### ISSUE TITLE
💥 Create Dune Dashboard to Track Usage Metrics

### ISSUE THREAD

**Issue by mds1** [pcaversaccio/createx#72]
### Describe the desired feature:

It would be nice to see stats per chain, and aggregated across all chains (that Dune supports), such as:

1. Total deployments,
2. Count of `CREATE` vs. `CREATE2` vs. `CREAT3` deployments,
3. Count of regular vs. EIP-1167 deployments,
4. Counts of each non-view method calls.

Open to other ideas for metrics too.

**Comment by YamenMerhi** [comment]
@mds1 @pcaversaccio Started drafting something here: 
https://dune.com/patronumlabs/createx

**Comment by pcaversaccio** [comment]
> @mds1 @pcaversaccio Started drafting something here: 
> https://dune.com/patronumlabs/createx

Sweet - let me add the link tomorrow to the `README`. You/we can keep finetuning the dashboards over next weeks.

**Comment by pcaversaccio** [comment]
@YamenMerhi see here: https://github.com/pcaversaccio/createx/pull/127 (when I merge, it will close this issue). Would be cool if you could add in the future:
- The number of all deployments across all supported chains.
- The number of all `CREATE`, `CREATE2`, `CREATE3`, and EIP-1167 deployments across all supported chains.
- Track the deployments of clones vs. normal contracts for each deployment method (as you already have as a TBD in your dashboard).
