### ISSUE TITLE
➕ Add OP-Endurance Test Network

### ISSUE THREAD

**Issue by shelchin2023** [pcaversaccio/createx#74]
### Chain Name

Op-Endurance-Testnet

### Chain ID

6480001001

### RPC URL

https://rpc-l2-testnet.fusionist.io/

### Block Explorer URL

https://explorer-l2-testnet.fusionist.io/

### Deployment Funds

Yes

**Comment by pcaversaccio** [comment]
For the record:

- Their GitHub repository: https://github.com/OpenFusionist.
- I verified that their contract creation is EVM equivalent using the following contract creation transaction: https://explorer-l2-testnet.fusionist.io/tx/0x8d7aed9ef7cfcb339bd5299be5d090daa69d1429859a78de006b4fd1fc863e5f

![image](https://github.com/pcaversaccio/createx/assets/25297591/990256cb-58cb-44d4-9dda-b38912f5ce6d)

![image](https://github.com/pcaversaccio/createx/assets/25297591/5e42a35a-700a-4de5-8fef-b7e9cff4fe41)

![image](https://github.com/pcaversaccio/createx/assets/25297591/9ba590ad-8d09-4187-aecc-e7d4eddffd46)

Will move forward now with the deployment.

**Comment by pcaversaccio** [comment]
Deployed and verified here: https://explorer-l2-testnet.fusionist.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed?tab=contract.

**Comment by pcaversaccio** [comment]
Will be added via https://github.com/pcaversaccio/createx/pull/76.
