### ISSUE TITLE
➕ Add Blast Test Network Deployment

### ISSUE THREAD

**Issue by ItsCuzzo** [pcaversaccio/createx#82]
### Chain Name

Blast Sepolia

### Chain ID

168587773

### RPC URL

https://sepolia.blast.io/

### Block Explorer URL

https://testnet.blastscan.io/

### Deployment Funds

Yes

**Comment by pcaversaccio** [comment]
Deployed: [`0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed`](https://testnet.blastscan.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
