### ISSUE TITLE
➕ Add DOS Chain Test and Main Network Deployments

### ISSUE THREAD

**Issue by JOY** [pcaversaccio/createx#91]
### Chain Name

DOS Chain

### Chain ID

7979

### RPC URL

https://main.doschain.com

### Block Explorer URL

https://doscan.io

### Deployment Funds

No

**Comment by pcaversaccio** [comment]
@JOY can you please quickly answer the following question: DOS Chain is fully EVM-compatible?

Can you please send 0.3 DOS to the deployer address `0xeD456e05CaAb11d66C4c797dD6c1D6f9A7F352b5`?

Also, I saw you have a test network. Do you also want `CreateX` to be deployed there (usually I deploy also on test networks)? If yes, please also send 0.3 ETH to the above deployer address on your test network.

**Comment by JOY** [comment]
Hi @pcaversaccio Yes, it is an Avalanche subnet, so it is fully EVM-compatible.
I assume that you are talking about 0.3 DOS, not ETH, so I send both on mainnet and testnet of DOS to that wallet.

Thank you for your support.

**Comment by pcaversaccio** [comment]
> Hi @pcaversaccio Yes, it is an Avalanche subnet, so it is fully EVM-compatible. I assume that you are talking about 0.3 DOS, not ETH, so I send both on mainnet and testnet of DOS to that wallet.
> 
> Thank you for your support.

Deployed (and verified on all running block explorers, including [routescan](https://7979.routescan.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed/contract/7979/code)). See https://github.com/pcaversaccio/createx/pull/93 for the details. Thanks for funding the deployments!
