### ISSUE TITLE
➕ Add Fraxtal Testnet Deployment

### ISSUE THREAD

**Issue by ArchieLenx** [pcaversaccio/createx#94]
### Chain Name

Fraxtal Testnet

### Chain ID

2522

### RPC URL

https://rpc.testnet.frax.com

### Block Explorer URL

https://holesky.fraxscan.com

### Deployment Funds

Yes

**Comment by ArchieLenx** [comment]
Wasnt able to get around the EIP155 requirement of the testnet RPC to deploy myself

**Comment by pcaversaccio** [comment]
@ArchieLenx here we go: https://holesky.fraxscan.com/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed. Will be merged via https://github.com/pcaversaccio/createx/pull/93 (but you can already use it obviously 😄).

**Comment by ArchieLenx** [comment]
HOW DID YOU GET PAST EIP155

**Comment by pcaversaccio** [comment]
> HOW DID YOU GET PAST EIP155

https://github.com/pcaversaccio/createx/discussions/61#discussioncomment-7937359
