### ISSUE TITLE
💥 Compute Vanity Addresses

### ISSUE THREAD

**Issue by JOY** [pcaversaccio/createx#95]
### Describe the desired feature:

Hi,

In the past, my developers employed Create2 to precompute the vanity address, with a pleasing format such as 0x9999... But it seems that we cannot do that with CreateX.
Are we missing something or CreateX hasn't supported that feature yet?

**Comment by pcaversaccio** [comment]
You can compute the vanity addresses for `CreateX` using https://github.com/HrikB/createXcrunch. Is this what you're looking for?

**Comment by JOY** [comment]
Let us try CreateXCrunch and will update here

**Comment by pcaversaccio** [comment]
> Let us try CreateXCrunch and will update here

You can deploy things like this 4 bytes zero leading contract https://etherscan.io/tx/0xd4f95266511547b6e7173a5a28614ce9a2374641fec79bee3720234bd9f03199#internal. So I think that's what you're searching for.

**Comment by pcaversaccio** [comment]
> hi @pcaversaccio, we use CreateXCrunch get saft: 0xba5ed099633d3b313e4d5f7bdc1305d3c28ba5ed01a34e9a3b1e51ff03e017bc => **0x7979a19d6613a4a95c76b82a47989c388fa126c7** and want deploy contract 0x7979a19d6613a4a95c76b82a47989c388fa126c7 on multi chain like dostest, fuji. But when i use createX deploy (createX[`deployCreate2(bytes32,bytes)`](salt, bytecode)) ) , i get different contract i want. https://test.doscan.io/tx/0xb32084b5ff12055058e7e36f2d7a40aa8f123bf2118a20a76d84406b1c763907. Please help me check it? Thank bro!

So in that case, the `salt` is again `keccak256` hashed before invoking `CREATE2`. Please go through the special features we have built here: https://github.com/pcaversaccio/createx#permissioned-deploy-protection-and-cross-chain-redeploy-protection. In your case, the final `salt` used will be:

```solidity
salt = keccak256(abi.encode(salt))
```

https://github.com/pcaversaccio/createx/blob/main/src/CreateX.sol#L910

**Comment by pcaversaccio** [comment]
@Dien-DOS I quickly checked your deployment transaction. `createXcrunch` cli already gives you the correct contract address (so you don't have to calculate it yourself) but you put the wrong salt. Compare the one you pasted here with the one in the transaction. They are not the same.

**Comment by Dien-DOS** [comment]
thank @pcaversaccio , We are trying your way! and will update here.

**Comment by Dien-DOS** [comment]
thank bro! problem is resolved! @pcaversaccio

**Comment by pcaversaccio** [comment]
> thank bro! problem is resolved! @pcaversaccio 

What was the bug?

**Comment by Dien-DOS** [comment]
saft i deploy wrong, fix salt = keccak256(abi.encode(salt))!

**Comment by pcaversaccio** [comment]
Ok, will close accordingly 👍
