### ISSUE TITLE
🐛 No Way to Avoid Salt Being Re-Hashed

### ISSUE THREAD

**Issue by Philogy** [pcaversaccio/createx#98]
### Describe the issue:

When supplying a salt in e.g. `deployCreate2(bytes32, bytes)` the salt is re-hashed in the `_guard` function. This is super annoying as it:
1. Makes CreateX incompatible with common salt minters such as [`create2crunch`](https://github.com/0age/create2crunch) (although the cross-chain protection byte requires a minor modification)
2. Causes a 2x slow-down in vanity address mining (makes address derivation require 2x keccak hashes rather than just 1 with normal create2)

Maybe I'm just being stupid and missing the obvious method that lets you do a CREATE2 deployment while being able to directly choose the salt but I can't see it.

### Code example to reproduce the issue:

Relevant code:

```diff
    function _guard(bytes32 salt) internal view returns (bytes32 guardedSalt) {
        (SenderBytes senderBytes, RedeployProtectionFlag redeployProtectionFlag) = _parseSalt({salt: salt});

        if (senderBytes == SenderBytes.MsgSender && redeployProtectionFlag == RedeployProtectionFlag.True) {
            // Configures a permissioned deploy protection as well as a cross-chain redeploy protection.
-           guardedSalt = keccak256(abi.encode(msg.sender, block.chainid, salt));
        } else if (senderBytes == SenderBytes.MsgSender && redeployProtectionFlag == RedeployProtectionFlag.False) {
            // Configures solely a permissioned deploy protection.
-           guardedSalt = _efficientHash({a: bytes32(uint256(uint160(msg.sender))), b: salt});
        } else if (senderBytes == SenderBytes.MsgSender) {
            // Reverts if the 21st byte is greater than `0x01` in order to enforce developer explicitness.
            revert InvalidSalt({emitter: _SELF});
        } else if (senderBytes == SenderBytes.ZeroAddress && redeployProtectionFlag == RedeployProtectionFlag.True) {
            // Configures solely a cross-chain redeploy protection. In order to prevent a pseudo-randomly
            // generated cross-chain redeploy protection, we enforce the zero address check for the first 20 bytes.
-           guardedSalt = _efficientHash({a: bytes32(block.chainid), b: salt});
        } else if (
            senderBytes == SenderBytes.ZeroAddress && redeployProtectionFlag == RedeployProtectionFlag.Unspecified
        ) {
            // Reverts if the 21st byte is greater than `0x01` in order to enforce developer explicitness.
            revert InvalidSalt({emitter: _SELF});
        } else {
            // For the non-pseudo-random cases, the salt value `salt` is hashed to prevent the safeguard mechanisms
            // from being bypassed. Otherwise, the salt value `salt` is not modified.
-           guardedSalt = (salt != _generateSalt()) ? keccak256(abi.encode(salt)) : salt;
        }
    }
```

**Comment by pcaversaccio** [comment]
@Philogy this is a feature and _not_ a bug. That's our design to implement safely a permissioned deploy protection and cross-chain redeploy protection (see [here](https://github.com/pcaversaccio/createx#permissioned-deploy-protection-and-cross-chain-redeploy-protection). We built on purpose our own cruncher [`createXcrunch`](https://github.com/HrikB/createXcrunch) to accomodate for these features, where you not only can mine for leading zeros, or containg zeros, but also pattern-matching addresses. If you don't like it, fair, I can offer my predecessor of `CreateX`, called [`Create2Deployer`](https://github.com/pcaversaccio/create2deployer) (that one is added as a predeploy in the OP stack fyi).

**Comment by Philogy** [comment]
Yeah specifically in the last case, not sure I fully understand the purpose of doing `keccak256(abi.encode(salt))`. What safety feature are you hoping people won't bypass? 

The pre-image is still public and anyone else can still redeploy on other chains using the un-hashed salt by running it through the function themselves, I just don't understand this part, what's the value of the extra hash?

**Comment by pcaversaccio** [comment]
> Yeah specifically in the last case, not sure I fully understand the purpose of doing `keccak256(abi.encode(salt))`. What safety feature are you hoping people won't bypass?

So let's make an example:
- On chain `A` I deploy a contract using a permissioned deploy protection. This will give me the final `salt`:

```solidity
guardedSalt = _efficientHash({a: bytes32(uint256(uint160(msg.sender))), b: salt});
```

- Someone else sees this deployment, and can calculate the `guardedSalt` (or simply copy it from a transaction debugger). This person deploys the same initcode with the `guardedSalt` as input. Since the `msg.sender` doesn't match in the `if else` statement in the `_guard` the code would lead him to the final `else` statement. If we didn't hash here the `salt`, he would be able to deploy the same initcode from his address even though the original deployment configured a permissioned deploy protection (i.e. it's only me who can deploy it). Does this make sense?
